version: '3.8'

services:

  mongo_cart:
    image: mongo:6.0
    container_name: trainingDev_cart_db
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_cart_data:/data/db

volumes:
  mongo_cart_data:


